package generator

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"

	"github.com/auremsinistram/go-errgen/pkg/tools"
	"github.com/auremsinistram/go-errors"

	domain "github.com/auremsinistram/go-errgen/internal/generator/domain"
)

type usecase struct {
	inputPath    *string
	econstPath   *string
	responsePath *string
	errorName    *string
}

func New(
	inputPath *string,
	econstPath *string,
	responsePath *string,
	errorName *string,
) domain.Usecase {
	return &usecase{
		inputPath:    inputPath,
		econstPath:   econstPath,
		responsePath: responsePath,
		errorName:    errorName,
	}
}

func (u *usecase) Generate() error {
	if *u.inputPath == "" {
		return errors.New("input path is required")
	}

	if *u.econstPath == "" {
		return errors.New("econst path is required")
	}

	if *u.responsePath == "" {
		return errors.New("response path is required")
	}

	if ext := filepath.Ext(*u.inputPath); ext != ".json" {
		return errors.Errorf("input file must have .json extension (got %q)", ext)
	}

	if ext := filepath.Ext(*u.econstPath); ext != ".go" {
		return errors.Errorf("econst file must have .go extension (got %q)", ext)
	}

	if ext := filepath.Ext(*u.responsePath); ext != ".json" {
		return errors.Errorf("response file must have .json extension (got %q)", ext)
	}

	if _, err := os.Stat(*u.inputPath); err != nil {
		return errors.Wrap(err, "usecase - Generate - #1")
	}

	inputData, err := os.ReadFile(*u.inputPath)
	if err != nil {
		return errors.Wrap(err, "usecase - Generate - #2")
	}

	econstData, responseData, err := u.generate(inputData)
	if err != nil {
		return errors.Wrap(err, "usecase - Generate - #3")
	}

	if err := tools.CheckDir(*u.econstPath); err != nil {
		return errors.Wrap(err, "usecase - Generate - #4")
	}

	if err := tools.CheckDir(*u.responsePath); err != nil {
		return errors.Wrap(err, "usecase - Generate - #5")
	}

	if err := os.WriteFile(*u.econstPath, econstData, 0644); err != nil {
		return errors.Wrap(err, "usecase - Generate - #6")
	}

	if err := os.WriteFile(*u.responsePath, responseData, 0644); err != nil {
		return errors.Wrap(err, "usecase - Generate - #7")
	}

	return nil
}

func (u *usecase) generate(data []byte) ([]byte, []byte, error) {
	var (
		inputErrors []domain.InputError

		econst   bytes.Buffer
		errConst bytes.Buffer
		errData  bytes.Buffer
		errRes   bytes.Buffer
	)

	if err := json.Unmarshal(data, &inputErrors); err != nil {
		return nil, nil, err
	}

	sort.Slice(inputErrors, func(i, j int) bool {
		return inputErrors[i].Name < inputErrors[j].Name
	})

	response := make(map[int]map[string]string)

	for i := range inputErrors {
		value := &inputErrors[i]
		name := tools.PascalCase(value.Name)
		code := tools.Code(name)

		fmt.Fprintf(
			&errConst,
			"\t%s = %d\n",
			name,
			code,
		)

		fmt.Fprintf(
			&errData,
			"\t%d: {\n\t\tstatus: %d,\n\t\tmessage: \"%s\",\n\t},\n",
			code,
			value.Status,
			value.Name,
		)

		if value.Name == *u.errorName {
			response := &domain.Response{
				Success: false,
				Error: domain.ErrorResponse{
					Code:    code,
					Message: value.Name,
				},
			}

			bytes, err := json.Marshal(response)
			if err != nil {
				return nil, nil, errors.Wrap(err, "usecase - generate - #1")
			}

			jsonBytes, err := tools.CompactJSON(bytes)
			if err != nil {
				return nil, nil, errors.Wrap(err, "usecase - generate - #2")
			}

			errRes.WriteString("var ErrRes = []byte(`")
			errRes.Write(jsonBytes)
			errRes.WriteString("`)")
		}

		response[code] = value.Messages
	}

	econst.WriteString("// Code generated by errgen. DO NOT EDIT.\n")
	econst.WriteString("package econst\n\n")
	econst.WriteString("type ErrorData struct {\n\tstatus int\n\n\tmessage string\n}\n\n")
	econst.WriteString("func (e *ErrorData) Status() int {\n\treturn e.status\n}\n\n")
	econst.WriteString("func (e *ErrorData) Message() string {\n\treturn e.message\n}\n\n")
	econst.WriteString("const (\n")
	econst.Write(errConst.Bytes())
	econst.WriteString(")\n\n")
	econst.WriteString("var ErrData = map[int]*ErrorData{\n")
	econst.Write(errData.Bytes())
	econst.WriteString("}\n\n")
	econst.Write(errRes.Bytes())
	econst.WriteString("\n")

	econstBytes, err := format.Source(econst.Bytes())
	if err != nil {
		return nil, nil, errors.Wrap(err, "usecase - generate - #3")
	}

	responseBytes, err := json.MarshalIndent(response, "", "    ")
	if err != nil {
		return nil, nil, errors.Wrap(err, "usecase - generate - #4")
	}

	return econstBytes, responseBytes, nil
}
